//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Demo.Core.Models.ModelsBuilder
{
	// Mixin content Type 1082 with alias "hideInNavDT"
	/// <summary>HideInNavDT</summary>
	public partial interface IHideInNavDT : IPublishedContent
	{
		/// <summary>Skjul i navigasjon</summary>
		bool HideInNavigation { get; }
	}

	/// <summary>HideInNavDT</summary>
	[PublishedContentModel("hideInNavDT")]
	public partial class HideInNavDT : PublishedContentModel, IHideInNavDT
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hideInNavDT";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HideInNavDT(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HideInNavDT, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Skjul i navigasjon
		///</summary>
		[ImplementPropertyType("hideInNavigation")]
		public bool HideInNavigation
		{
			get { return GetHideInNavigation(this); }
		}

		/// <summary>Static getter for Skjul i navigasjon</summary>
		public static bool GetHideInNavigation(IHideInNavDT that) { return that.GetPropertyValue<bool>("hideInNavigation"); }
	}
}
